import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff8f1",
    paddingTop: 48,
  },
  headerCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    borderRadius: 24,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 3,
  },
  eyebrow: {
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#a3412b",
    marginBottom: 8,
  },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#2b211b",
    marginBottom: 8,
  },
  description: {
    fontSize: 16,
    lineHeight: 22,
    color: "#6b5243",
  },
  summaryCard: {
    marginTop: 16,
    padding: 16,
    borderRadius: 18,
    backgroundColor: "#f7ebe1",
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    color: "#8f503d",
    marginBottom: 6,
  },
  summaryName: {
    fontSize: 24,
    fontWeight: "800",
    color: "#2b211b",
    marginBottom: 4,
  },
  summaryMeta: {
    fontSize: 16,
    color: "#6b5243",
    marginBottom: 6,
  },
  summaryDistance: {
    fontSize: 18,
    fontWeight: "700",
    color: "#a3412b",
  },
  coordinates: {
    marginTop: 14,
    fontSize: 15,
    color: "#4e3a30",
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
  },
  loadingText: {
    fontSize: 15,
    color: "#6b5243",
  },
  mapView: {
    flex: 1,
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 24,
  },
  fallbackPanel: {
    flex: 1,
    marginHorizontal: 16,
    marginBottom: 16,
    marginTop: 16,
    borderRadius: 20,
    backgroundColor: "#fff",
    padding: 20,
    justifyContent: "center",
    minHeight: 300,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 3,
  },
  fallbackTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#3d2a1f",
    marginBottom: 8,
  },
  fallbackBody: {
    fontSize: 16,
    lineHeight: 22,
    color: "#6b5243",
    marginBottom: 20,
  },
  coordinateList: {
    gap: 10,
  },
  coordinateItem: {
    fontSize: 16,
    color: "#2b211b",
  },
});